#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Rules
bspc rule -a firefox desktop='^2'
bspc rule -a Chromium desktop='^3'
bspc rule -a vlc desktop='^10'
bspc rule -a Emacs state=tiled desktop='^6'

bspc rule -a mpv \
     state=floating sticky=on follow=off focus=on \
     rectangle=640x360+1253+695

bspc rule -a "*:Toolkit:Picture-in-Picture" \
     state=floating sticky=on follow=off focus=on \
     rectangle=640x360+1253+695

bspc config top_padding 45

# borders
bspc config focused_border_color "#353b45"
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle true

#gaps 
bspc config gapless_monocle true
bspc config window_gap 20
bspc config split_ratio 0.50

# Pointer actions
bspc config pointer_modifier mod4
bspc config pointer_action1 move

feh --bg-fill ~/Pictures/wallpaper/freezydreamin-SV3V-D1G2q4-unsplash.jpg

# eww for widgets
~/.bin/eww daemon

# polybar 
cp -r ~/Public/poly/bsp/polybar ~/.config/ &
~/.config/polybar/launch.sh &

# picom as compositor
picom --experimental-backend --config ~/.config/picom/picom.conf
